# Generated by Django 4.2.4 on 2023-08-02 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habit',
            name='action',
            field=models.CharField(max_length=100, verbose_name='Действие (привычка)'),
        ),
    ]
