# Generated by Django 4.2.4 on 2023-08-08 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_user_managers'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='tg_nickname',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Никнейм в телеграм'),
        ),
    ]
